config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'pages#home'
  
  get 'about' => 'pages#about'
  get 'faq' => 'pages#faq'

  resources :conversations, only: [:index] do
    resources :messages, only: :create
  end
  resources :interests
  resources :matches
  resources :interests
  resources :interests_users

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	belongs_to :user1, class_name: "User"
	belongs_to :user2, class_name: "User"
	has_many :messages, dependent: :destroy

	def users
	  return [user1, user2]
	end

	def other_user(user)
	  users.include?(user) ? (users - [user]).first : nil
	end

	def unread_messages(user)
	  messages.where(user: other_user(user), read_at: nil)
	end

	def unread_messages_count(user)
	  unread_messages(user).count
	end

	def unread_messages?(user)
	  unread_messages_count(user) > 0
	end

	def last_message
	  messages.order(created_at: :asc).last
	end
end

app/models/interest.rb
class Interest < ActiveRecord::Base
	has_many :user_interests
  	has_many :users, through: :user_interests
end

app/models/match.rb
class Match < ActiveRecord::Base
	belongs_to :user1, class_name: "User"
	belongs_to :user2, class_name: "User"
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :conversation

  validates :content, presence: true
  validates :conversation, presence: true
  validates :user, inclusion: { in: :users }

  def mark_as_read
    self.read_at = DateTime.now
    self.save
  end

  def users
    conversation.users
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_interests, dependent: :destroy
  has_many :interests, through: :user_interests, dependent: :destroy
  has_many :messages, dependent: :destroy

  def conversations
    Conversation.includes(:messages)
                .where("user1_id = :id OR user2_id = :id", id: id)
                .order("messages.created_at DESC")
  end

  def other_user(conversation)
    conversation.users.include?(self) ? conversation.other_user(self) : nil
  end

  def unread_conversations
    conversations.select { |c| c.unread_messages?(self) }
  end

  def unread_conversations_count
    unread_conversations.count
  end

  def unread_conversations?
    unread_conversations_count > 0
  end

  def one_avatar_url
    avatar_url ? avatar_url : "http://placehold.it/64x64"
  end
end

app/models/user_interest.rb
class UserInterest < ActiveRecord::Base
	belongs_to :user
 	belongs_to :interest
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @conversations = current_user.conversations
    if params[:conversation_id]
      @selected_conversation = @conversations.find(params[:conversation_id])
    else
      @selected_conversation = @conversations.first
    end
    @unread_messages = @selected_conversation.unread_messages(current_user)
    @unread_messages.each { |message| message.mark_as_read }
    @unread_conversations_count = current_user.unread_conversations_count
  end
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @selected_conversation = Conversation.find(params[:conversation_id])
    @message = Message.new(message_params)
    @message.user = current_user
    @message.conversation = @selected_conversation
    @message.save
    @conversations = current_user.conversations
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def faq
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
# check this tutorial if it doesn't work: http://jacopretorius.net/2014/03/adding-custom-fields-to-your-devise-user-model-in-rails-4.html

	private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :age, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :age, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/user_interests_helper.rb
module UserInterestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Happenstance</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<%= render 'shared/flashes' %>



<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag("logo.png", :alt => "logo") %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Text link -->
    <a href="" class="navbar-wagon-item navbar-wagon-link">Contact</a>

    <!-- Text link -->
    <a href="" class="navbar-wagon-item navbar-wagon-link">Team</a>

    <!-- Notification link-->
    <div class="navbar-wagon-item navbar-wagon-link">
      <div class="badge-container">
        <%= link_to conversations_path do %>
          <i class="fa fa-envelope-o"></i>
        <% end %>
        <% if user_signed_in? && current_user.unread_conversations? %>
          <div class="badge badge-blue"><%= @unread_conversations_count %></div>
        <% end %>
      </div>
    </div>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
      <% if user_signed_in? %>
        <%= image_tag current_user.one_avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
      <% end %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li>
            <% if user_signed_in? %>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            <% else %>
              <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
    <a href="" class="navbar-wagon-item navbar-wagon-button btn">Match me!</a>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <% if user_signed_in? %>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
            <% end %>
          <% else %>
            <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>